baseURL = "https://ntduan.github.io"
languageCode = "zh-cn"
title = "NT"
copyright = "Copyright &copy; 2020 - Nantian Duan"
canonifyurls = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "paraiso-dark"

googleAnalytics = "" #Google Analytics ID

[author]
    name = "Nantian Duan"
    github = "https://github.com/ntduan"

[params]
    tagline = "..."
    customCSS = []
    disableDarkModeCSS = false